# Generated by Django 2.2.10 on 2020-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('parents', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertUserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(help_text='Please do not enter shortened links here.')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(max_length=20000)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=15, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_videos', to='categories.Board')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='categories.ExpertUserVideoCategory')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_user_videos', to='experts.ExpertUserProfile')),
                ('likes', models.ManyToManyField(blank=True, db_index=True, related_name='user_liked_videos', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_vidoes', to='categories.SubCategory')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.Tagged', to='tags.CustomTag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Expert User Video',
                'verbose_name_plural': 'Expert User Videos',
                'ordering': ['-pinned'],
            },
        ),
        migrations.CreateModel(
            name='ExpertVideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anonymous_user', models.CharField(blank=True, help_text='Full Name for non logged in users', max_length=255, null=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_user_video_comments', to='experts.ExpertUserProfile')),
                ('likes', models.ManyToManyField(db_index=True, related_name='user_liked_video_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_user_video_comments', to='parents.ParentProfile')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_expert_video_comment_childrens', to='videos.ExpertVideoComment')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_comments', to='videos.ExpertUserVideo')),
            ],
            options={
                'verbose_name': 'Expert Video Comment',
                'verbose_name_plural': 'Expert Video Comments',
            },
        ),
    ]
