# Generated by Django 2.2.10 on 2022-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_expertuservideo_youtube_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuservideo',
            name='last_views_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
