# Generated by Django 2.2.10 on 2021-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_uniform_app',
            field=models.BooleanField(default=False),
        ),
    ]
