# Generated by Django 2.2.10 on 2021-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_uniform_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_facebook_user',
            field=models.BooleanField(default=False),
        ),
    ]
