# Generated by Django 2.2.10 on 2022-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_facebook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
