# Generated by Django 2.2.10 on 2020-08-10 15:40

import admission_informations.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInformationArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mini_title', models.CharField(blank=True, max_length=80, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=admission_informations.utils.admission_information_article_upload_path)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(max_length=20000)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Information Article',
                'verbose_name_plural': 'Admission Information Articles',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInformationArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anonymous_user', models.CharField(blank=True, help_text='Full Name for non logged in users', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Admission Information Article Comment',
                'verbose_name_plural': 'Admission Information Article Comments',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInformationNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('mini_title', models.CharField(blank=True, max_length=80, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=admission_informations.utils.admission_information_news_thumbnail_upload_path)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Admission Inforamtion News',
                'verbose_name_plural': 'Admission Inforamtion News',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInformationNewsHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Inforamtion News Headline',
                'verbose_name_plural': 'Admission Inforamtion News Headlines',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInformationUserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(help_text='Please do not enter shortened links here.')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(max_length=20000)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=15, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Information Expert User Video',
                'verbose_name_plural': 'Admission Information Expert User Videos',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInformationVideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anonymous_user', models.CharField(blank=True, help_text='Full Name for non logged in users', max_length=255, null=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_user_admission_video_comments', to='experts.ExpertUserProfile')),
                ('likes', models.ManyToManyField(db_index=True, related_name='user_liked_admission_video_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Information Expert Video Comment',
                'verbose_name_plural': 'Admission Information Expert Video Comments',
            },
        ),
    ]
