# Generated by Django 2.2.10 on 2020-08-10 15:40

from django.db import migrations, models
import django.db.models.deletion
import news.utils
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('experts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('mini_title', models.CharField(blank=True, max_length=80, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=news.utils.news_thumbnail_upload_path)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=15, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_news', to='experts.ExpertUserProfile')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_news', to='categories.Board')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.Tagged', to='tags.CustomTag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='news.News')),
            ],
            options={
                'verbose_name': 'News Headline',
                'verbose_name_plural': 'News Headlines',
            },
        ),
    ]
