# Generated by Django 2.2.10 on 2020-09-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumb_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Alt Text'),
        ),
    ]
