# Generated by Django 2.2.10 on 2021-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_thumb_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='for_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
