# Generated by Django 2.2.10 on 2020-05-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.BooleanField(default=False)),
                ('parenting', models.BooleanField(default=False)),
                ('quiz', models.BooleanField(default=False)),
                ('admission', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID')),
                ('email', models.EmailField(blank=True, help_text='To be used for anonymous user', max_length=254, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('W', 'Weekly'), ('D', 'Daily')], max_length=10, null=True)),
                ('group', models.CharField(choices=[('A', 'Admission'), ('P', 'Parenting'), ('N', 'News'), ('Q', 'Quiz')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_date', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletters.Preference')),
            ],
        ),
    ]
