# Generated by Django 2.2.10 on 2020-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20200531_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
