# Generated by Django 2.2.10 on 2020-12-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_preference_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='family_annual_income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
