# Generated by Django 2.2.10 on 2020-08-10 15:40

import admission_forms.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childs', '0004_auto_20200516_1905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0011_auto_20200720_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildSchoolCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='General', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('single_child', models.BooleanField(blank=True, null=True)),
                ('first_child', models.BooleanField(blank=True, null=True)),
                ('single_parent', models.BooleanField(blank=True, null=True)),
                ('first_girl_child', models.BooleanField(blank=True, null=True)),
                ('staff_ward', models.BooleanField(blank=True, null=True)),
                ('sibling1_alumni_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sibling2_alumni_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sibling1_alumni_proof', models.ImageField(blank=True, null=True, upload_to=admission_forms.utils.sibling1_alumni_proof_upload_path)),
                ('sibling2_alumni_proof', models.ImageField(blank=True, null=True, upload_to=admission_forms.utils.sibling2_alumni_proof_upload_path)),
                ('lockstatus', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_admission_forms', to='childs.Child')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default='', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Not Accepted')], default='Pending', max_length=10)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('distance_points', models.IntegerField(blank=True, null=True)),
                ('single_child_points', models.IntegerField(blank=True, null=True)),
                ('siblings_studied_points', models.IntegerField(blank=True, null=True)),
                ('parents_alumni_points', models.IntegerField(blank=True, null=True)),
                ('staff_ward_points', models.IntegerField(blank=True, null=True)),
                ('first_born_child_points', models.IntegerField(blank=True, null=True)),
                ('first_girl_child_points', models.IntegerField(blank=True, null=True)),
                ('single_girl_child_points', models.IntegerField(blank=True, null=True)),
                ('christian_points', models.IntegerField(blank=True, null=True)),
                ('viewed', models.BooleanField(blank=True, db_index=True, default=False)),
                ('girl_child_point', models.IntegerField(blank=True, default=0)),
                ('single_parent_point', models.IntegerField(blank=True, default=0)),
                ('minority_points', models.IntegerField(blank=True, default=0)),
                ('student_with_special_needs_points', models.IntegerField(blank=True, default=0)),
                ('children_of_armed_force_points', models.IntegerField(blank=True, default=0)),
                ('apply_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolClasses')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='childs.Child')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_reg_form', to='admission_forms.CommonRegistrationForm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='schools.SchoolProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='FormReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(db_index=True, max_length=25)),
                ('form_fee', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school_applied', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='admission_forms.SchoolApplication')),
            ],
        ),
    ]
