# Generated by Django 2.2.10 on 2020-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission_forms', '0001_initial'),
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('childs', '0004_auto_20200516_1905'),
        ('schools', '0011_auto_20200720_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationform',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_admission_forms', to='parents.ParentProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_admission_forms', to='parents.ParentProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_admission_forms', to='parents.ParentProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='sibling1_alumni_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling1_school_name', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='sibling2_alumni_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling2_school_name', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_admission_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childschoolcart',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_cart', to='childs.Child'),
        ),
        migrations.AddField(
            model_name='childschoolcart',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission_forms.CommonRegistrationForm'),
        ),
        migrations.AddField(
            model_name='childschoolcart',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_forms.CommonRegistrationForm'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_point', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='schools_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_forms.SchoolApplication'),
        ),
        migrations.AlterUniqueTogether(
            name='childschoolcart',
            unique_together={('child', 'school')},
        ),
    ]
