# Generated by Django 2.2.10 on 2021-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0003_auto_20200905_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='childschoolcart',
            name='form_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
