# Generated by Django 2.2.10 on 2021-01-28 06:13

import admission_forms.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_auto_20210128_1143'),
        ('childs', '0004_auto_20200516_1905'),
        ('admission_forms', '0004_childschoolcart_form_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(choices=[('C', 'Collab'), ('N', 'Non-Collab')], default='C', max_length=10)),
                ('mail_content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='childschoolcart',
            options={'verbose_name': 'Child School Cart Item', 'verbose_name_plural': 'Child School Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='commonregistrationform',
            options={'verbose_name': 'Common Registration Form', 'verbose_name_plural': 'Common Registration Forms'},
        ),
        migrations.AlterModelOptions(
            name='formreceipt',
            options={'verbose_name': 'Form Receipt', 'verbose_name_plural': 'Form Receipts'},
        ),
        migrations.AlterModelOptions(
            name='schoolapplication',
            options={'ordering': ('-timestamp',), 'verbose_name': 'School Application', 'verbose_name_plural': 'School Applications'},
        ),
        migrations.RemoveField(
            model_name='schoolapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='last_school_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='last_school_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolBoard'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='last_school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolClasses'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='last_school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='transfer_certificate',
            field=models.ImageField(blank=True, null=True, upload_to=admission_forms.utils.transfer_certificate_upload_path),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Transfer Certificate SNo.'),
        ),
        migrations.CreateModel(
            name='ChildSchoolEvaluatedPointsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_child_points', models.IntegerField(default=0)),
                ('siblings_points', models.IntegerField(default=0)),
                ('parent_alumni_points', models.IntegerField(default=0)),
                ('staff_ward_points', models.IntegerField(default=0)),
                ('first_born_child_points', models.IntegerField(default=0)),
                ('first_girl_child_points', models.IntegerField(default=0)),
                ('single_girl_child_points', models.IntegerField(default=0)),
                ('is_christian_points', models.IntegerField(default=0)),
                ('girl_child_points', models.IntegerField(default=0)),
                ('single_parent_points', models.IntegerField(default=0)),
                ('minority_points', models.IntegerField(default=0)),
                ('student_with_special_needs_points', models.IntegerField(default=0)),
                ('children_of_armed_force_points', models.IntegerField(default=0)),
                ('distance_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_school_points', to='childs.Child')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ChildSchoolDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=5, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childs.Child')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolProfile')),
            ],
            options={
                'verbose_name': 'Child School Distance',
                'verbose_name_plural': 'Child School Distances',
            },
        ),
        migrations.CreateModel(
            name='ChildPointsPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('single_child_points', models.BooleanField(blank=True, null=True)),
                ('siblings_points', models.BooleanField(blank=True, null=True)),
                ('parent_alumni_points', models.BooleanField(blank=True, null=True)),
                ('staff_ward_points', models.BooleanField(blank=True, null=True)),
                ('first_born_child_points', models.BooleanField(blank=True, null=True)),
                ('first_girl_child_points', models.BooleanField(blank=True, null=True)),
                ('single_girl_child_points', models.BooleanField(blank=True, null=True)),
                ('is_christian_points', models.BooleanField(blank=True, null=True)),
                ('girl_child_points', models.BooleanField(blank=True, null=True)),
                ('single_parent_points', models.BooleanField(blank=True, null=True)),
                ('minority_points', models.BooleanField(blank=True, null=True)),
                ('student_with_special_needs_points', models.BooleanField(blank=True, null=True)),
                ('children_of_armed_force_points', models.BooleanField(blank=True, null=True)),
                ('short_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_points', to='childs.Child')),
            ],
            options={
                'verbose_name': 'Child Points Preference',
                'verbose_name_plural': 'Child Points Preferences',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='admission_forms.SchoolApplication')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admission_forms.ApplicationStatus')),
            ],
        ),
    ]
