# Generated by Django 2.2.10 on 2021-02-12 12:40

import admission_forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0005_auto_20210128_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationform',
            name='last_school_result_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='reason_of_leaving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='report_card',
            field=models.ImageField(blank=True, null=True, upload_to=admission_forms.utils.report_card_upload_path),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='transport_facility_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
