# Generated by Django 2.2.10 on 2021-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0006_auto_20210212_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationform',
            name='latitude_secondary',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='longitude_secondary',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
