# Generated by Django 2.2.10 on 2021-02-13 11:51

import admission_forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0007_auto_20210213_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolapplication',
            name='non_collab_receipt',
            field=models.FileField(blank=True, null=True, upload_to=admission_forms.utils.non_collab_receipt_upload_path),
        ),
    ]
