# Generated by Django 2.2.10 on 2021-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0008_schoolapplication_non_collab_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='sms_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
