# Generated by Django 2.2.10 on 2021-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0009_applicationstatus_sms_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolapplication',
            name='transport_facility_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
