# Generated by Django 2.2.10 on 2021-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0013_commonregistrationform_single_parent_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolapplication',
            name='calculated_distance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
