# Generated by Django 2.2.10 on 2021-02-21 17:25

import admission_forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0014_schoolapplication_calculated_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationform',
            name='caste_category_certificate',
            field=models.ImageField(blank=True, null=True, upload_to=admission_forms.utils.caste_category_certificate_upload_path),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='is_twins',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='second_born_child',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='third_born_child',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
