# Generated by Django 2.2.10 on 2021-02-24 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0015_auto_20210221_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childschoolevaluatedpointscheck',
            name='child',
        ),
        migrations.RemoveField(
            model_name='childschoolevaluatedpointscheck',
            name='school',
        ),
        migrations.RemoveField(
            model_name='childpointspreference',
            name='attempts',
        ),
        migrations.AddField(
            model_name='childpointspreference',
            name='latitude_secondary',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='childpointspreference',
            name='longitude_secondary',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='childpointspreference',
            name='transport_facility_points',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childpointspreference',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChildSchoolDistance',
        ),
        migrations.DeleteModel(
            name='ChildSchoolEvaluatedPointsCheck',
        ),
    ]
