# Generated by Django 2.2.10 on 2021-03-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0038_schoolprofile_count_start'),
        ('admission_forms', '0016_auto_20210224_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPointsPreferenceSchoolWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(blank=True, default=0)),
                ('children_of_armed_force_points', models.IntegerField(blank=True, default=0)),
                ('single_child_points', models.IntegerField(blank=True, default=0)),
                ('siblings_points', models.IntegerField(blank=True, default=0)),
                ('parent_alumni_points', models.IntegerField(blank=True, default=0)),
                ('staff_ward_points', models.IntegerField(blank=True, default=0)),
                ('first_born_child_points', models.IntegerField(blank=True, default=0)),
                ('first_girl_child_points', models.IntegerField(blank=True, default=0)),
                ('single_girl_child_points', models.IntegerField(blank=True, default=0)),
                ('is_christian_points', models.IntegerField(blank=True, default=0)),
                ('girl_child_points', models.IntegerField(blank=True, default=0)),
                ('single_parent_points', models.IntegerField(blank=True, default=0)),
                ('minority_points', models.IntegerField(blank=True, default=0)),
                ('student_with_special_needs_points', models.IntegerField(blank=True, default=0)),
                ('transport_facility_points', models.IntegerField(blank=True, default=0)),
                ('distance_points', models.IntegerField(blank=True, default=0)),
                ('points_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointspref', to='admission_forms.ChildPointsPreference')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.SchoolProfile')),
            ],
            options={
                'verbose_name': 'Child Points School Preference',
                'verbose_name_plural': 'Child Points School Preferences',
            },
        ),
    ]
