# Generated by Django 2.2.10 on 2021-03-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0017_childpointspreferenceschoolwise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childpointspreferenceschoolwise',
            old_name='points_preference',
            new_name='pref',
        ),
    ]
