# Generated by Django 2.2.10 on 2021-03-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0018_auto_20210303_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonregistrationform',
            old_name='mother_tounge',
            new_name='mother_tongue',
        ),
    ]
