# Generated by Django 2.2.10 on 2021-06-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0022_schoolapplication_registration_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonregistrationformafterpayment',
            name='child_slug',
        ),
        migrations.RemoveField(
            model_name='commonregistrationformafterpayment',
            name='father_slug',
        ),
        migrations.RemoveField(
            model_name='commonregistrationformafterpayment',
            name='guardian_slug',
        ),
        migrations.RemoveField(
            model_name='commonregistrationformafterpayment',
            name='mother_slug',
        ),
    ]
