# Generated by Django 2.2.10 on 2021-10-19 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0027_auto_20211005_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childschoolcart',
            name='session',
            field=models.CharField(blank=True, default='2021-2022', help_text='ex YYYY-YYYY', max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='commonregistrationform',
            name='session',
            field=models.CharField(blank=True, default='2021-2022', help_text='ex YYYY-YYYY', max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='commonregistrationformafterpayment',
            name='session',
            field=models.CharField(blank=True, default='2021-2022', help_text='ex YYYY-YYYY', max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session'),
        ),
    ]
