# Generated by Django 2.2.10 on 2021-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0028_auto_20211019_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='child_intre_state_transfer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_covid_vaccination_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_frontline_helper',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_covid_vaccination_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_frontline_helper',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_covid_vaccination_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_frontline_helper',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='father_covid_19_frontline_warrior_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='father_covid_vacination_certifiacte_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='guardian_covid_19_frontline_warrior_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='guardian_covid_vacination_certifiacte_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='mother_covid_19_frontline_warrior_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='mother_covid_vacination_certifiacte_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='state_transfer_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
