# Generated by Django 2.2.10 on 2021-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0029_auto_20211222_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonregistrationformafterpayment',
            name='child_intre_state_transfer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
