# Generated by Django 2.2.10 on 2022-02-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0030_auto_20211222_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='child_illness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
