# Generated by Django 2.2.10 on 2022-02-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0031_commonregistrationformafterpayment_child_illness'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
