# Generated by Django 2.2.10 on 2022-02-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0094_auto_20220214_1402'),
        ('admission_forms', '0032_auto_20220214_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistrationform',
            name='father_staff_ward_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='father_staff_ward_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_staff_ward_school', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='father_staff_ward_tenure',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='father_type_of_staff_ward',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='guardian_staff_ward_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='guardian_staff_ward_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_staff_ward_school', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='guardian_staff_ward_tenure',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='guardian_type_of_staff_ward',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='mother_staff_ward_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='mother_staff_ward_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_staff_ward_school', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='mother_staff_ward_tenure',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationform',
            name='mother_type_of_staff_ward',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_staff_ward_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_staff_ward_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_staff_ward_school_after_pay', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_staff_ward_tenure',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='father_type_of_staff_ward',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_staff_ward_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_staff_ward_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_staff_ward_school_after_pay', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_staff_ward_tenure',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='guardian_type_of_staff_ward',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_staff_ward_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_staff_ward_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_staff_ward_school_after_pay', to='schools.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_staff_ward_tenure',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonregistrationformafterpayment',
            name='mother_type_of_staff_ward',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
