# Generated by Django 2.2.10 on 2022-03-25 05:18

import admission_forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0034_auto_20220321_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonregistrationform',
            name='parent_signature_upload',
            field=models.FileField(blank=True, null=True, upload_to=admission_forms.utils.parent_signature_upload_path),
        ),
        migrations.AlterField(
            model_name='commonregistrationformafterpayment',
            name='parent_signature_upload',
            field=models.FileField(blank=True, null=True, upload_to=admission_forms.utils.parent_signature_upload_path),
        ),
    ]
