# Generated by Django 2.2.10 on 2022-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_forms', '0035_auto_20220325_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formreceipt',
            name='receipt_id',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='schoolapplication',
            name='uid',
            field=models.CharField(db_index=True, default='', max_length=70),
        ),
    ]
