version: '3'
services:
  web:
    build: .
    command: python ezyschoolingbackend/manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web

volumes:
  pgdata:
  redisdata: