# Generated by Django 2.2.10 on 2020-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('anonymous_user', models.CharField(blank=True, help_text='Full Name for non logged in users', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=20000, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
            },
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anonymous_user', models.CharField(blank=True, help_text='Full Name for non logged in users', max_length=255, null=True)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments', to='discussions.Discussion')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_user_discussion_comments', to='experts.ExpertUserProfile')),
                ('likes', models.ManyToManyField(db_index=True, related_name='user_liked_discussion_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Comment',
                'verbose_name_plural': 'Discussion Comments',
            },
        ),
    ]
