# Generated by Django 2.2.10 on 2022-03-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0103_auto_20220311_1106'),
        ('admin_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorCAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data_permission', models.BooleanField(default=False)),
                ('enquiry_data_permission', models.BooleanField(default=False)),
                ('school_profile_data_permission', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.District')),
                ('district_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.DistrictRegion')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.States')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.CAdminUser')),
            ],
            options={
                'verbose_name': 'Counselor User',
                'verbose_name_plural': 'Counselor Users',
            },
        ),
    ]
