# Generated by Django 2.2.10 on 2022-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0003_auto_20220305_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorcadminuser',
            name='city',
            field=models.ManyToManyField(blank=True, to='schools.City'),
        ),
        migrations.AlterField(
            model_name='counselorcadminuser',
            name='district',
            field=models.ManyToManyField(blank=True, to='schools.District'),
        ),
        migrations.AlterField(
            model_name='counselorcadminuser',
            name='district_region',
            field=models.ManyToManyField(blank=True, to='schools.DistrictRegion'),
        ),
    ]
