# Generated by Django 2.2.10 on 2022-04-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_custom', '0005_auto_20220324_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselingaction',
            old_name='child_action',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='counselingaction',
            old_name='created_at',
            new_name='action_created_at',
        ),
        migrations.RenameField(
            model_name='counselingaction',
            old_name='updated_at',
            new_name='action_updated_at',
        ),
        migrations.RenameField(
            model_name='counselingaction',
            old_name='child_scheduled_time',
            new_name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='counselingaction',
            name='child_data',
        ),
        migrations.AddField(
            model_name='actionsection',
            name='requires_datetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counselorcadminuser',
            name='boarding_schools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counselorcadminuser',
            name='online_schools',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionsection',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubActionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('requires_datetime', models.BooleanField(default=False)),
                ('action_realtion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_action', to='admin_custom.ActionSection')),
            ],
        ),
        migrations.CreateModel(
            name='LeadGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text="User's Name", max_length=150, null=True)),
                ('user_phone_number', models.TextField(blank=True, help_text='number', null=True)),
                ('user_email', models.TextField(blank=True, help_text='email', null=True)),
                ('classes', models.CharField(blank=True, help_text='classes', max_length=60, null=True)),
                ('budget', models.CharField(blank=True, help_text='budget', max_length=75, null=True)),
                ('location', models.CharField(blank=True, help_text='location', max_length=150, null=True)),
                ('lead_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lead_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('counseling_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.CounselorCAdminUser', verbose_name='Counseling Action User')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolEnquiry', verbose_name='enquiry_data')),
                ('lead_for', models.ManyToManyField(blank=True, related_name='lead_generated_schools', to='schools.SchoolProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='counselingaction',
            name='sub_actiom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.SubActionSection'),
        ),
    ]
