# Generated by Django 2.2.10 on 2022-04-12 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_custom', '0006_auto_20220407_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitScheduleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text="User's Name", max_length=150, null=True)),
                ('user_phone_number', models.TextField(blank=True, help_text='number', null=True)),
                ('user_email', models.TextField(blank=True, help_text='email', null=True)),
                ('walk_in_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('walk_in_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('counseling_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.CounselorCAdminUser', verbose_name='Counseling Action User')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolEnquiry', verbose_name='enquiry_data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('walk_in_for', models.ManyToManyField(blank=True, related_name='walk_in_schools', to='schools.SchoolProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text="User's Name", max_length=150, null=True)),
                ('user_phone_number', models.TextField(blank=True, help_text='number', null=True)),
                ('user_email', models.TextField(blank=True, help_text='email', null=True)),
                ('admissiomn_done_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('admissiomn_done_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('admission_done_for', models.ManyToManyField(blank=True, related_name='admission_done_in_schools', to='schools.SchoolProfile')),
                ('counseling_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.CounselorCAdminUser', verbose_name='Counseling Action User')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolEnquiry', verbose_name='enquiry_data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
