# Generated by Django 2.2.10 on 2022-04-12 11:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0007_admissiondonedata_visitscheduledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingaction',
            name='first_action',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
