# Generated by Django 2.2.10 on 2022-04-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0008_counselingaction_first_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorDailyCallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_calls', models.PositiveIntegerField(default=0)),
                ('anonymous_enquiry_calls', models.PositiveIntegerField(default=0)),
                ('user_calls', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.CounselorCAdminUser', verbose_name='Counsellor')),
            ],
        ),
    ]
