# Generated by Django 2.2.10 on 2022-04-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0009_counsellordailycallrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellordailycallrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='counsellordailycallrecord',
            name='first_call_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellordailycallrecord',
            name='latest_call_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
