# Generated by Django 2.2.10 on 2022-04-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0012_auto_20220414_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcommentsection',
            name='admissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.AdmissionDoneData'),
        ),
        migrations.AddField(
            model_name='schoolcommentsection',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.LeadGenerated'),
        ),
        migrations.AddField(
            model_name='schoolcommentsection',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.VisitScheduleData'),
        ),
    ]
