# Generated by Django 2.2.10 on 2022-04-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0013_auto_20220415_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolaction',
            name='first_action',
        ),
        migrations.AddField(
            model_name='schoolaction',
            name='admissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.AdmissionDoneData'),
        ),
        migrations.AddField(
            model_name='schoolaction',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.LeadGenerated'),
        ),
        migrations.AddField(
            model_name='schoolaction',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.VisitScheduleData'),
        ),
    ]
