# Generated by Django 2.2.10 on 2022-06-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0015_schoolperformedactiononenquiry_schoolperformedcommentenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseCAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_permission', models.BooleanField(default=False)),
                ('edit_permission', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.CAdminUser')),
            ],
            options={
                'verbose_name': 'DB Team User',
                'verbose_name_plural': 'DB Team Users',
            },
        ),
    ]
