# Generated by Django 2.2.10 on 2022-06-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_custom', '0017_viewedparentphonenumberbyschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCallScheduled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.CharField(blank=True, max_length=512, null=True)),
                ('time_slot', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='admissiondonedata',
            name='call_scheduled_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_call_scheduled_admission_done_data', to='admin_custom.ParentCallScheduled'),
        ),
        migrations.AddField(
            model_name='commentsection',
            name='call_scheduled_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_call_scheduled_comment_data', to='admin_custom.ParentCallScheduled'),
        ),
        migrations.AddField(
            model_name='counselingaction',
            name='call_scheduled_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_call_scheduled_counseling_data', to='admin_custom.ParentCallScheduled'),
        ),
        migrations.AddField(
            model_name='leadgenerated',
            name='call_scheduled_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_call_scheduled_lead_data', to='admin_custom.ParentCallScheduled'),
        ),
        migrations.AddField(
            model_name='visitscheduledata',
            name='call_scheduled_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_call_scheduled_visit_scheduled_data', to='admin_custom.ParentCallScheduled'),
        ),
    ]
