# Generated by Django 2.2.10 on 2022-07-23 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0120_auto_20220723_1114'),
        ('admin_custom', '0018_auto_20220628_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondonedata',
            name='child_name',
            field=models.CharField(blank=True, help_text='Child Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolperformedactiononenquiry',
            name='child_name',
            field=models.CharField(blank=True, help_text='Child Name', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='TransferredCounsellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('call_scheduled_by_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_counsellor_parent_call_scheduled', to='admin_custom.ParentCallScheduled')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolEnquiry')),
                ('transfer_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='admin_custom.CounselorCAdminUser', verbose_name='Transfer By')),
                ('transfer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_by', to='admin_custom.CounselorCAdminUser', verbose_name='Transfer To')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCounsellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('call_scheduled_by_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_counsellor_parent_call_scheduled', to='admin_custom.ParentCallScheduled')),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_counsellor', to='admin_custom.CounselorCAdminUser', verbose_name='Counsellor')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolEnquiry')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_with', to='admin_custom.CounselorCAdminUser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
