# Generated by Django 2.2.10 on 2022-07-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0019_auto_20220723_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorcadminuser',
            name='unassigned_call_data_permission',
            field=models.BooleanField(default=False),
        ),
    ]
