# Generated by Django 2.2.10 on 2022-08-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0020_counselorcadminuser_unassigned_call_data_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsection',
            name='considered_as_call_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subactionsection',
            name='considered_as_call_done',
            field=models.BooleanField(default=False),
        ),
    ]
