# Generated by Django 2.2.10 on 2020-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200423_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=28.6448, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=77.216721, max_digits=22, null=True),
        ),
    ]
