# Generated by Django 2.2.9 on 2020-05-06 13:02

from django.db import migrations, models
import schools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200428_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='cover',
            field=models.ImageField(blank=True, default='schools/cover/default.png', null=True, upload_to=schools.utils.school_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, help_text="Please compress the images before uploading using this <a href='https://www.iloveimg.com/compress-image'>tool</a>.", null=True, upload_to=schools.utils.school_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, default='schools/logos/default.png', null=True, upload_to=schools.utils.school_logo_upload_path),
        ),
    ]
