# Generated by Django 2.2.9 on 2020-05-06 14:14

from django.db import migrations, models
import schools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20200506_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='cover',
            field=models.ImageField(blank=True, default='schools/cover/default.jpg', null=True, upload_to=schools.utils.school_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, default='schools/logos/default.jpg', null=True, upload_to=schools.utils.school_logo_upload_path),
        ),
    ]
