# Generated by Django 2.2.10 on 2020-07-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_region_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='views_permission',
            field=models.BooleanField(default=False, verbose_name='School Views Permission'),
        ),
    ]
