# Generated by Django 2.2.10 on 2020-07-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0010_schoolprofile_views_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='enquiry_permission',
            field=models.BooleanField(default=False, verbose_name='School Enquiry Permission'),
        ),
        migrations.CreateModel(
            name='SchoolEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('query', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='schools.SchoolProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Enquiry',
                'verbose_name_plural': 'School Enquiries',
            },
        ),
    ]
