# Generated by Django 2.2.10 on 2020-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20200720_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
