# Generated by Django 2.2.10 on 2020-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20200813_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School Verification Code',
                'verbose_name_plural': 'School Verification Codes',
            },
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
