# Generated by Django 2.2.10 on 2020-08-18 22:30

from django.db import migrations, models
import schools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20200815_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, default='schools/logos/default.png', null=True, upload_to=schools.utils.school_logo_upload_path),
        ),
    ]
