# Generated by Django 2.2.10 on 2020-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_schoolprofile_short_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
