# Generated by Django 2.2.10 on 2020-09-22 14:50

from django.db import migrations, models
import schools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_schoolprofile_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=schools.utils.school_region_photo_upload_path),
        ),
    ]
