# Generated by Django 2.2.10 on 2020-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_region_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
