# Generated by Django 2.2.10 on 2020-10-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_acitivityautocomplete_activitytypeautocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='ownership',
            field=models.CharField(blank=True, choices=[('G', 'Government'), ('P', 'Private')], max_length=5, null=True),
        ),
    ]
