# Generated by Django 2.2.16 on 2020-11-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20201029_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='academic_session',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='medium',
            field=models.CharField(choices=[('E', 'English'), ('H', 'Hindi')], default='E', max_length=10, verbose_name='Medium of Instruction'),
        ),
    ]
