# Generated by Django 2.2.16 on 2020-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_auto_20201104_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='convenience_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
