# Generated by Django 2.2.16 on 2020-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_schoolprofile_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='rank',
            new_name='region_rank',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='sort_id',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='global_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
