# Generated by Django 2.2.10 on 2020-12-17 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0027_auto_20201214_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdmissionAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolClasses')),
                ('school_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Admission Alert',
                'verbose_name_plural': 'School Admission Alerts',
            },
        ),
    ]
