# Generated by Django 2.2.10 on 2020-12-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_schooladmissionalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admmissionopenclasses',
            name='admission_open',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('ABOUT TO CLOSE', 'ABOUT TO CLOSE'), ('CLOSE', 'CLOSE')], default='CLOSE', max_length=15, null=True),
        ),
    ]
