# Generated by Django 2.2.10 on 2021-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_auto_20201225_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=80, verbose_name='school_regions'),
        ),
    ]
