# Generated by Django 2.2.10 on 2021-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_auto_20210115_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmissionformfee',
            name='form_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
