# Generated by Django 2.2.10 on 2021-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_schooladmissionformfee_form_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admmissionopenclasses',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
