# Generated by Django 2.2.10 on 2021-01-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_auto_20210119_1656'),
        ('schools', '0032_auto_20210115_1803'),
    ]

    operations = [
    ]
