# Generated by Django 2.2.10 on 2021-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_auto_20210128_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_boardss',
            field=models.ManyToManyField(blank=True, related_name='schools', to='schools.SchoolBoard'),
        ),
    ]
