# Generated by Django 2.2.10 on 2021-02-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_schoolprofile_school_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'School Fees Type',
            },
        ),
        migrations.CreateModel(
            name='SchoolStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SchoolFeesParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('refundable', models.BooleanField(default=False, null=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolFeesType')),
            ],
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fees_parameters',
            field=models.ManyToManyField(blank=True, related_name='feestructure', to='schools.SchoolFeesParameters'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='stream_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolStream'),
        ),
    ]
