# Generated by Django 2.2.10 on 2021-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_schoolprofile_school_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpoint',
            name='transport_facility_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
