# Generated by Django 2.2.10 on 2021-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_auto_20210218_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='count_start',
            field=models.IntegerField(default=0),
        ),
    ]
