# Generated by Django 2.2.10 on 2021-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0038_schoolprofile_count_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='video',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='video_tour_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
