# Generated by Django 2.2.10 on 2021-04-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_appliedschoolselectedcsv_selectedstudentfromcsv'),
        ('schools', '0036_auto_20210209_1822'),
    ]

    operations = [
    ]
