# Generated by Django 2.2.16 on 2021-04-02 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_appliedschoolselectedcsv_selectedstudentfromcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolenquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_enquiry', to=settings.AUTH_USER_MODEL),
        ),
    ]
