# Generated by Django 2.2.10 on 2021-04-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0041_merge_20210405_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeesparameters',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_fees_parameter', to='schools.SchoolProfile'),
        ),
    ]
