# Generated by Django 2.2.10 on 2021-04-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0042_schoolfeesparameters_school'),
        ('schools', '0041_auto_20210402_1054'),
    ]

    operations = [
    ]
