# Generated by Django 2.2.10 on 2021-04-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0043_merge_20210410_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_fee_structure', to='schools.SchoolProfile'),
        ),
    ]
