# Generated by Django 2.2.10 on 2021-04-21 08:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import schools.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0044_auto_20210421_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=schools.utils.school_city_photo_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=schools.utils.school_country_photo_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=schools.utils.school_district_photo_upload_path)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=schools.utils.school_states_photo_upload_path)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Country')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=schools.utils.school_district_region_photo_upload_path)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.District')),
                ('pincode', models.ManyToManyField(blank=True, to='schools.Pincode')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.States')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.States'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.States'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='school_area')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=schools.utils.school_area_photo_upload_path)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.District')),
                ('district_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.DistrictRegion')),
                ('pincode', models.ManyToManyField(blank=True, to='schools.Pincode')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.States')),
            ],
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Pincode'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Area'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Country'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.District'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_district_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.DistrictRegion'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.States'),
        ),
    ]
