# Generated by Django 2.2.10 on 2021-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0046_auto_20210427_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltype',
            name='order_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
