# Generated by Django 2.2.10 on 2021-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0047_schooltype_order_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='district_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='district_region_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='states_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
