# Generated by Django 2.2.16 on 2021-05-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0048_auto_20210515_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
