# Generated by Django 2.2.10 on 2021-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0050_feature_featurename_subfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='filter_string',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
