# Generated by Django 2.2.16 on 2021-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0051_feature_filter_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolenquiry',
            name='query',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
