# Generated by Django 2.2.16 on 2021-07-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0052_auto_20210703_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Schools Subject',
                'verbose_name_plural': 'Schools Subjects',
            },
        ),
    ]
