# Generated by Django 2.2.10 on 2021-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0059_auto_20211004_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admmissionopenclasses',
            unique_together={('class_relation', 'school', 'session')},
        ),
    ]
