# Generated by Django 2.2.10 on 2021-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('schools', '0061_auto_20211005_1155'),
        ('schools', '0060_auto_20211004_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admmissionopenclasses',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
