# Generated by Django 2.2.10 on 2021-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0063_auto_20211005_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='admmissionopenclasses',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='admmissionopenclasses',
            unique_together={('class_relation', 'school', 'session')},
        ),
    ]
