# Generated by Django 2.2.10 on 2021-10-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('schools', '0068_auto_20211009_1112'),
        ('schools', '0067_auto_20211005_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_relation', 'school', 'session', 'stream_relation')},
        ),
    ]
