# Generated by Django 2.2.10 on 2021-10-19 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0069_auto_20211009_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsession',
            name='name',
            field=models.CharField(help_text='ex format YYYY-YYYY', max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session year'),
        ),
        migrations.AlterField(
            model_name='admmissionopenclasses',
            name='session',
            field=models.CharField(blank=True, default='2021-2022', help_text='ex YYYY-YYYY', max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='session',
            field=models.CharField(blank=True, default='2021-2022', help_text='ex YYYY-YYYY', max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
    ]
