# Generated by Django 2.2.10 on 2021-10-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0070_auto_20211019_1440'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_relation', 'school', 'session', 'stream_relation')},
        ),
    ]
