# Generated by Django 2.2.10 on 2021-11-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0072_auto_20211108_1626'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
