# Generated by Django 2.2.10 on 2021-11-15 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0073_auto_20211109_1238'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
        migrations.CreateModel(
            name='SchoolClassNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session', models.CharField(blank=True, default='2021-2022', help_text='ex 2021-2022, 2022-2023', max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Input Correct Format', regex='^.{9}$')], verbose_name='Session')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notify_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_classes', to='schools.SchoolClasses')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notifications', to='schools.SchoolProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Class Notifications',
                'verbose_name_plural': 'School Class Notifications',
            },
        ),
    ]
