# Generated by Django 2.2.10 on 2021-11-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0075_auto_20211118_1509'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
