# Generated by Django 2.2.10 on 2021-11-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0076_auto_20211122_1327'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
        migrations.CreateModel(
            name='VideoTourLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(help_text='Seprate multiple links using comma(,) . Also do not use space in between the links', verbose_name='Links')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolProfile')),
            ],
            options={
                'verbose_name': 'Video Tour Link ',
                'verbose_name_plural': 'Video Tour Links',
            },
        ),
    ]
