# Generated by Django 2.2.10 on 2021-12-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0078_auto_20211129_1550'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
