# Generated by Django 2.2.10 on 2021-12-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0079_auto_20211202_1746'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
