# Generated by Django 2.2.10 on 2021-12-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0080_auto_20211210_1122'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
