# Generated by Django 2.2.10 on 2021-12-22 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0081_auto_20211210_1433'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
        migrations.CreateModel(
            name='GroupedSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schools', models.ManyToManyField(blank=True, to='schools.SchoolProfile')),
            ],
            options={
                'verbose_name': 'Grouped School',
                'verbose_name_plural': 'Grouped Schools',
            },
        ),
    ]
