# Generated by Django 2.2.10 on 2021-12-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0083_auto_20211222_1616'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
