# Generated by Django 2.2.10 on 2022-01-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_auto_20211222_1726'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
