# Generated by Django 2.2.10 on 2022-01-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0085_auto_20220103_1606'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
