# Generated by Django 2.2.10 on 2022-01-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0086_auto_20220113_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='common_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
