# Generated by Django 2.2.10 on 2022-02-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0089_auto_20220203_1103'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
