# Generated by Django 2.2.10 on 2022-02-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0090_auto_20220205_1611'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
