# Generated by Django 2.2.10 on 2022-02-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0092_auto_20220207_1130'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
