# Generated by Django 2.2.10 on 2022-02-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0093_auto_20220214_1256'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
