# Generated by Django 2.2.10 on 2022-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0094_auto_20220214_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='views_check_permission',
            field=models.BooleanField(default=False, verbose_name='School Views Permission'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='views_permission',
            field=models.BooleanField(default=False, verbose_name='School Cart Data Permission'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
