# Generated by Django 2.2.10 on 2022-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0095_auto_20220216_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Other', 'Other'), ('Category', 'Category')], default='Other', max_length=15, null=True),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
