# Generated by Django 2.2.10 on 2022-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0099_auto_20220223_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolenquiry',
            name='source',
            field=models.CharField(default='general', max_length=50),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
