# Generated by Django 2.2.10 on 2022-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0100_auto_20220301_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeesparameters',
            name='range',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='schoolfeesparameters',
            name='upper_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
