# Generated by Django 2.2.10 on 2022-03-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0103_auto_20220311_1106'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
