# Generated by Django 2.2.10 on 2022-03-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0104_auto_20220324_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolenquiry',
            name='class_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_class_relation_enquiry', to='schools.SchoolClasses'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='agecriteria',
        #     unique_together={('school', 'class_relation', 'session')},
        # ),
    ]
