# Generated by Django 2.2.10 on 2022-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0105_auto_20220331_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtregion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='districtregion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
