# Generated by Django 2.2.10 on 2022-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0107_auto_20220408_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='counselling_data_permission',
            field=models.BooleanField(default=False, verbose_name='Counselling Data Permission'),
        ),
    ]
