# Generated by Django 2.2.10 on 2022-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0108_auto_20220421_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='built_in_area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='language_options', to='schools.Language'),
        ),
    ]
