# Generated by Django 2.2.10 on 2022-06-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0111_auto_20220531_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='send_whatsapp_notification',
            field=models.BooleanField(default=False, verbose_name='Whatsapp Message Notification Permission'),
        ),
        migrations.CreateModel(
            name='SchoolClaimRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolProfile')),
            ],
            options={
                'verbose_name': 'School Claim Request',
                'verbose_name_plural': 'School Claim Requests',
            },
        ),
    ]
