# Generated by Django 2.2.10 on 2022-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0112_auto_20220603_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclaimrequests',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
