# Generated by Django 2.2.10 on 2022-06-08 11:22

from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0113_auto_20220604_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMultiClassRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_class_relation', models.ManyToManyField(blank=True, related_name='school_multiple_class_relation', to='schools.SchoolClasses')),
                ('unique_class_relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_unique_class_relation', to='schools.SchoolClasses', validators=[schools.models.validate_unique_class_relation])),
            ],
            options={
                'verbose_name': 'School Multi Class Relation',
                'verbose_name_plural': 'School Multi Classes Relation',
            },
        ),
    ]
