# Generated by Django 2.2.10 on 2022-07-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0115_auto_20220623_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEqnuirySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100, unique=True)),
                ('related_id', models.CharField(max_length=200, unique=True,blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ad Source ID',
                'verbose_name_plural': 'Ad Source IDs',
            },
        ),
        migrations.AddField(
            model_name='schoolenquiry',
            name='ad_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
