# Generated by Django 2.2.10 on 2022-07-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0116_auto_20220701_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionpagecontent',
            name='district_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.DistrictRegion'),
        ),
    ]
