# Generated by Django 2.2.10 on 2022-07-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0118_auto_20220707_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooleqnuirysource',
            name='total_clicks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
