# Generated by Django 2.2.10 on 2022-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0119_auto_20220708_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='head_email_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
