# Generated by Django 2.2.10 on 2022-08-02 09:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0122_auto_20220801_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredOptionalSchoolFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_admission_form_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('required_child_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('required_father_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('required_mother_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('required_guardian_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_optional_school_fields', to='schools.SchoolProfile')),
            ],
            options={
                'verbose_name': 'Required Optional Application Field',
                'verbose_name_plural': 'Required Optional Application Fields',
            },
        ),
    ]
