# Generated by Django 2.2.10 on 2020-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
