# Generated by Django 2.2.10 on 2020-04-02 08:05

from django.db import migrations, models
import django.db.models.deletion
import miscs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(blank=True, null=True, upload_to=miscs.utils.activity_image_upload_path)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to=miscs.utils.activity_video_upload_path)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ezyschooling Activity',
                'verbose_name_plural': 'Ezyschooling Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarouselCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Carousel Categories',
            },
        ),
        migrations.CreateModel(
            name='EzySchoolingNewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=miscs.utils.carousel_image_upload_path)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ezyschooling News Article',
                'verbose_name_plural': 'Ezyschooling News Articles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=miscs.utils.carousel_image_upload_path)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscs.CarouselCategory')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'ordering': ['order'],
            },
        ),
    ]
