# Generated by Django 2.2.10 on 2020-04-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0002_activity_carousel_carouselcategory_ezyschoolingnewarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EzySchoolingNewArticle',
            new_name='EzySchoolingNewsArticle',
        ),
    ]
