# Generated by Django 2.2.10 on 2020-06-12 00:02

from django.db import migrations, models
import miscs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0006_auto_20200413_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(help_text='Link to event goes here.')),
                ('description', models.TextField(max_length=1000)),
                ('speaker_name', models.CharField(max_length=200)),
                ('speaker_photo', models.ImageField(blank=True, null=True, upload_to=miscs.utils.online_event_speaker_image_upload_path)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
