# Generated by Django 2.2.10 on 2020-07-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0008_auto_20200612_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('parent_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ezyschooling Achiever',
                'verbose_name_plural': 'Ezyschooling Achievers',
            },
        ),
    ]
