# Generated by Django 2.2.10 on 2020-07-09 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscs', '0009_achiever'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentHuntSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('public_id', models.TextField()),
                ('child_name', models.CharField(max_length=200)),
                ('parent_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, db_index=True, related_name='user_liked_talenthunt_video', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talent Hunt Submission',
                'verbose_name_plural': 'Talent Hunt Submissions',
            },
        ),
    ]
