# Generated by Django 2.2.10 on 2020-07-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0010_talenthuntsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talenthuntsubmission',
            old_name='public_id',
            new_name='video',
        ),
        migrations.AddField(
            model_name='talenthuntsubmission',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talenthuntsubmission',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
