# Generated by Django 2.2.10 on 2020-07-16 07:03

from django.db import migrations, models
import miscs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0011_auto_20200711_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=miscs.utils.carousel_image_upload_path),
        ),
    ]
