# Generated by Django 2.2.10 on 2020-08-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0013_faqanswer_faqcategory_faqquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
