# Generated by Django 2.2.10 on 2020-09-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0015_admissionguidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionguidance',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
