# Generated by Django 2.2.10 on 2020-09-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0016_auto_20200925_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
