# Generated by Django 2.2.10 on 2020-10-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0018_auto_20201007_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='talenthuntsubmission',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miscs.TalentHuntSubmission'),
        ),
    ]
