# Generated by Django 2.2.16 on 2020-12-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_auto_20201104_0743'),
        ('miscs', '0020_auto_20201202_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='schools.Region'),
        ),
    ]
