# Generated by Django 2.2.16 on 2020-12-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0021_faqquestion_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionGuidanceSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_slot', models.TimeField()),
                ('zoom_link', models.URLField(max_length=255)),
                ('meeting_id', models.CharField(help_text='Include the spaces in the ID, because it will be exactly how it will be shown to user in email.', max_length=255)),
                ('meeting_passcode', models.CharField(max_length=255)),
                ('event_date', models.DateField(help_text='Change the date for the latest version of the event here, this will be the date mentioned in the emails.')),
            ],
            options={
                'verbose_name': 'Admission Guidance Slot',
                'verbose_name_plural': 'Admission Guidance Slots',
            },
        ),
        migrations.AddField(
            model_name='admissionguidance',
            name='budget',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admissionguidance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miscs.AdmissionGuidanceSlot'),
        ),
    ]
