# Generated by Django 2.2.10 on 2020-12-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_auto_20201225_1149'),
        ('miscs', '0022_auto_20201215_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionGuidanceProgrammePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionGuidanceProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Region')),
            ],
            options={
                'verbose_name': 'Admission Guidance Programme',
                'verbose_name_plural': 'Admission Guidance Programme',
            },
        ),
    ]
