# Generated by Django 2.2.10 on 2021-01-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0025_surveytaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponses',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='miscs.SurveyTaker'),
        ),
    ]
