# Generated by Django 2.2.10 on 2021-04-29 09:24

from django.db import migrations, models
import miscs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0028_auto_20210429_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=miscs.utils.user_testimonial_upload_path)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Our Sponser',
                'verbose_name_plural': 'Our Sponser',
            },
        ),
    ]
