# Generated by Django 2.2.10 on 2021-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0029_oursponsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastandcurrentimpactinars',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorsregistrations',
            name='companyname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsorsregistrations',
            name='website_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarregistrations',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarregistrations',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarregistrations',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
