# Generated by Django 2.2.10 on 2021-05-01 05:23

from django.db import migrations, models
import miscs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0030_auto_20210430_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedprincipals',
            name='about_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastandcurrentimpactinars',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=miscs.utils.impactinar_upload_path),
        ),
    ]
