# Generated by Django 2.2.16 on 2021-05-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0048_auto_20210515_1530'),
        ('miscs', '0031_auto_20210501_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_city', to='schools.City'),
        ),
    ]
