# Generated by Django 2.2.16 on 2021-06-08 09:42

from django.db import migrations, models
import miscs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0032_faqquestion_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzyschoolingEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=miscs.utils.employee_img_upload_path)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedinurl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ezyschooling Employee',
                'verbose_name_plural': 'Ezyschooling Employees',
            },
        ),
    ]
