# Generated by Django 2.2.16 on 2021-06-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0034_pastandcurrentimpactinars_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastandcurrentimpactinars',
            name='status',
        ),
    ]
