# Generated by Django 2.2.16 on 2021-06-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0035_remove_pastandcurrentimpactinars_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastandcurrentimpactinars',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=15, null=True),
        ),
    ]
