# Generated by Django 2.2.16 on 2021-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0036_pastandcurrentimpactinars_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastandcurrentimpactinars',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
