# Generated by Django 2.2.16 on 2021-07-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0053_subjects'),
        ('miscs', '0037_pastandcurrentimpactinars_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_board', to='schools.SchoolBoard'),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_district', to='schools.District'),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='district_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_districtregion', to='schools.DistrictRegion'),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='school_category',
            field=models.CharField(blank=True, choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Coed', 'Coed')], default='Coed', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_school_type', to='schools.SchoolType'),
        ),
    ]
