# Generated by Django 2.2.16 on 2021-07-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0053_subjects'),
        ('miscs', '0038_auto_20210714_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='class_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_school_classes', to='schools.SchoolClasses'),
        ),
    ]
