# Generated by Django 2.2.16 on 2021-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0039_faqquestion_class_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=15, null=True),
        ),
    ]
