# Generated by Django 2.2.10 on 2020-03-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import experts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=experts.utils.expert_user_profile_picture_upload_path)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_expert_panel', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert User Profile',
                'verbose_name_plural': 'Expert User Profiles',
            },
        ),
    ]
