# Generated by Django 2.2.10 on 2022-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationdata',
            name='is_success',
        ),
        migrations.AddField(
            model_name='pushnotificationdata',
            name='click_action',
            field=models.URLField(blank=True, null=True),
        ),
    ]
