# Generated by Django 2.2.10 on 2022-05-20 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20220429_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatappSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Subscriber', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WhatappSubscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
