# Generated by Django 2.2.10 on 2022-05-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_whatappsubscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatappsubscribers',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WhatsappSubscribersViaEnquiry', to='schools.SchoolEnquiry'),
        ),
    ]
