# Generated by Django 2.2.10 on 2022-05-21 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_whatappsubscribers_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Subscriber', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WhatsappSubscribersViaEnquiry', to='schools.SchoolEnquiry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WhatsappSubscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Subscriber',
                'verbose_name_plural': 'WhatsApp Subscribers',
            },
        ),
        migrations.DeleteModel(
            name='WhatappSubscribers',
        ),
    ]
