# Generated by Django 2.2.10 on 2022-05-27 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_auto_20220521_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceregistrationtoken',
            old_name='registration_id',
            new_name='mobile_registration_id',
        ),
        migrations.AddField(
            model_name='deviceregistrationtoken',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City'),
        ),
        migrations.AddField(
            model_name='deviceregistrationtoken',
            name='is_boarding_school',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceregistrationtoken',
            name='is_online_school',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceregistrationtoken',
            name='pc_registration_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSelectedCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boarding_school', models.BooleanField(blank=True, null=True)),
                ('is_online_school', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
