# Generated by Django 2.2.10 on 2022-05-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20220527_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotificationdata',
            options={'verbose_name': 'Sent Notification', 'verbose_name_plural': 'Sent Notifications'},
        ),
        migrations.AlterModelOptions(
            name='userselectedcity',
            options={'verbose_name': "User's City", 'verbose_name_plural': 'User Cities'},
        ),
        migrations.AddField(
            model_name='pushnotificationdata',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.City'),
        ),
        migrations.AddField(
            model_name='pushnotificationdata',
            name='for_desktop_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushnotificationdata',
            name='for_mobile_users',
            field=models.BooleanField(default=False),
        ),
    ]
