# Generated by Django 2.2.10 on 2020-03-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tablet', models.BooleanField(blank=True, default=False, null=True)),
                ('is_touch_capable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pc', models.BooleanField(blank=True, default=False, null=True)),
                ('is_bot', models.BooleanField(blank=True, default=False, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version_string', models.CharField(blank=True, max_length=100, null=True)),
                ('os_family', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version_string', models.CharField(blank=True, max_length=100, null=True)),
                ('device_family', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Pages Visits',
                'ordering': ['-timestamp'],
            },
        ),
    ]
