# Generated by Django 2.2.10 on 2020-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analatics', '0002_clicklogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklogentry',
            name='next_page_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
