# Generated by Django 2.2.10 on 2020-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200930_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='meta_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
    ]
