# Generated by Django 2.2.10 on 2020-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='bookmarked_videos',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_parents', to='videos.ExpertUserVideo'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='follow_tags',
            field=models.ManyToManyField(blank=True, related_name='followers', to='tags.CustomTag'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentaddress',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_address', to='parents.ParentProfile'),
        ),
    ]
