# Generated by Django 2.2.10 on 2021-01-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_auto_20210119_1656'),
        ('parents', '0002_auto_20200810_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Region', to='schools.Region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='ParentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='parents.ParentProfile')),
            ],
        ),
    ]
