# Generated by Django 2.2.10 on 2021-01-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20210119_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenttracker',
            name='Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent_Address', to='parents.ParentAddress'),
        ),
    ]
