# Generated by Django 2.2.10 on 2021-01-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_auto_20210119_1656'),
        ('parents', '0004_parenttracker_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='parenttracker',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='parenttracker',
            name='Parent',
        ),
        migrations.AddField(
            model_name='parentaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='parenttracker',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.ParentAddress'),
        ),
        migrations.AddField(
            model_name='parenttracker',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.ParentProfile'),
        ),
        migrations.AlterField(
            model_name='parentaddress',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parentaddress',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parentaddress',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentaddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parentaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
