# Generated by Django 2.2.10 on 2021-01-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_auto_20210120_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
