# Generated by Django 2.2.10 on 2021-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_auto_20210128_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='passing_class',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
