# Generated by Django 2.2.10 on 2021-02-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_auto_20210211_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
