# Generated by Django 2.2.10 on 2021-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_auto_20210221_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='companyname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
