# Generated by Django 2.2.10 on 2021-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0011_parentprofile_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaddress',
            name='monthly_budget',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
