# Generated by Django 2.2.10 on 2021-04-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0012_parentaddress_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_address_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
