# Generated by Django 2.2.10 on 2021-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0014_auto_20210405_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='covid_vaccination_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='frontline_helper',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
