# Generated by Django 2.2.10 on 2020-03-26 12:55

import childs.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=childs.utils.child_profile_picture_upload_path)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to=childs.utils.child_birth_certificate_upload_path)),
                ('address_proof', models.ImageField(blank=True, null=True, upload_to=childs.utils.address_proof_upload_path)),
                ('first_child_affidavit', models.ImageField(blank=True, null=True, upload_to=childs.utils.first_child_affidavit_upload_path)),
                ('sibling1_alumni_proof', models.ImageField(blank=True, null=True, upload_to=childs.utils.sibling1_alumni_proof_upload_path)),
                ('sibling2_alumni_proof', models.ImageField(blank=True, null=True, upload_to=childs.utils.sibling2_alumni_proof_upload_path)),
                ('vaccination_card', models.ImageField(blank=True, null=True, upload_to=childs.utils.child_vaccination_card_upload_path)),
                ('is_christian', models.BooleanField(blank=True, default=False)),
                ('minority_points', models.BooleanField(blank=True, default=False)),
                ('student_with_special_needs_points', models.BooleanField(blank=True, default=False)),
                ('armed_force_points', models.BooleanField(blank=True, default=False)),
                ('orphan', models.BooleanField(default=False)),
                ('class_applying_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.SchoolClasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_childs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Profile',
                'verbose_name_plural': 'Child Profiles',
            },
        ),
    ]
