# Generated by Django 2.2.10 on 2020-04-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='sibling1_alumni_proof',
        ),
        migrations.RemoveField(
            model_name='child',
            name='sibling2_alumni_proof',
        ),
    ]
