# Generated by Django 2.2.10 on 2020-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0002_auto_20200429_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='no_school',
            field=models.BooleanField(default=False, verbose_name="Doesn't attend school"),
        ),
    ]
