# Generated by Django 2.2.10 on 2020-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0003_child_no_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='armed_force_points',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='is_christian',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='minority_points',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='orphan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='student_with_special_needs_points',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
