# Generated by Django 2.2.10 on 2021-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0004_auto_20200516_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
