# Generated by Django 2.2.10 on 2021-02-17 13:10

import childs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0005_child_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='minority_proof',
            field=models.ImageField(blank=True, null=True, upload_to=childs.utils.minority_proof_upload_path),
        ),
    ]
