# Generated by Django 2.2.10 on 2021-02-19 08:37

import childs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0006_child_minority_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='aadhaar_card_proof',
            field=models.ImageField(blank=True, null=True, upload_to=childs.utils.child_aadhar_card_path_upload_path),
        ),
        migrations.AddField(
            model_name='child',
            name='address_proof2',
            field=models.ImageField(blank=True, null=True, upload_to=childs.utils.address_proof_upload_path),
        ),
        migrations.AddField(
            model_name='child',
            name='armed_force_proof',
            field=models.ImageField(blank=True, null=True, upload_to=childs.utils.child_armed_force_proof_upload_path),
        ),
    ]
