# Generated by Django 2.2.10 on 2021-09-08 05:25

import childs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0008_auto_20210220_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='medical_certificate',
            field=models.ImageField(blank=True, null=True, upload_to=childs.utils.medical_fitness_certificate_upload_path),
        ),
    ]
