# Generated by Django 2.2.10 on 2022-02-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0010_child_intre_state_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='illness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
