# Generated by Django 2.2.10 on 2022-03-21 07:20

import childs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0011_child_illness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='aadhaar_card_proof',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.child_aadhar_card_path_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.address_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='address_proof2',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.address_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='armed_force_proof',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.child_armed_force_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.child_birth_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_child_affidavit',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.first_child_affidavit_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.medical_fitness_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='minority_proof',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.minority_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='child',
            name='vaccination_card',
            field=models.FileField(blank=True, null=True, upload_to=childs.utils.child_vaccination_card_upload_path),
        ),
    ]
