# Generated by Django 2.2.10 on 2020-08-10 15:40

import articles.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mini_title', models.CharField(blank=True, max_length=80, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=articles.utils.expert_article_upload_path)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(max_length=20000)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
                ('comment_counts', models.PositiveIntegerField(default=0)),
                ('like_counts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expert Article',
                'verbose_name_plural': 'Expert Articles',
                'ordering': ['-pinned'],
            },
        ),
        migrations.CreateModel(
            name='ExpertArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anonymous_user', models.CharField(blank=True, help_text='Full Name for non logged in users', max_length=255, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_comments', to='articles.ExpertArticle')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_users_expert_article_comment', to='experts.ExpertUserProfile')),
                ('likes', models.ManyToManyField(blank=True, db_index=True, related_name='user_liked_expert_article_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Article Comment',
                'verbose_name_plural': 'Expert Article Comments',
            },
        ),
    ]
