# Generated by Django 2.2.10 on 2020-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_expertarticle_thumb_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertarticle',
            name='meta_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
    ]
