# Generated by Django 2.2.10 on 2022-04-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_popupcategory'),
        ('articles', '0007_expertarticle_for_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertarticle',
            name='popup_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_articles_popup_details', to='categories.PopupCategory'),
        ),
    ]
