# Generated by Django 2.2.10 on 2021-11-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Tech / Marketing', max_length=200, verbose_name='Job Domain')),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Domain',
                'verbose_name_plural': 'Job Domains',
            },
        ),
        migrations.CreateModel(
            name='JobExperienceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(help_text='Ex. Fresher/ 2 Years / 2 - 4 Years', max_length=200, verbose_name='Experience Range')),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Experience Range',
                'verbose_name_plural': 'Job Experience Ranges',
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Delhi/Banglore', max_length=200, verbose_name='Location Name')),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Location',
                'verbose_name_plural': 'Job Locations',
            },
        ),
        migrations.CreateModel(
            name='JobSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(help_text='Ex. 3LPA / 6LPA', max_length=200, verbose_name='Job Salary')),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Experience Range',
                'verbose_name_plural': 'Job Experience Ranges',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Full Time/ Internship', max_length=200, verbose_name='Job type')),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Type',
                'verbose_name_plural': 'Job Types',
            },
        ),
    ]
