# Generated by Django 2.2.10 on 2021-11-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsalary',
            old_name='range',
            new_name='salary',
        ),
    ]
