# Generated by Django 2.2.10 on 2021-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20211109_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdomain',
            options={'verbose_name': 'Job Domains', 'verbose_name_plural': 'Job Domain'},
        ),
        migrations.AlterModelOptions(
            name='jobexperiencerange',
            options={'verbose_name': 'Job Experience Ranges', 'verbose_name_plural': 'Job Experience Range'},
        ),
        migrations.AlterModelOptions(
            name='joblocation',
            options={'verbose_name': 'Job Locations', 'verbose_name_plural': 'Job Location'},
        ),
        migrations.AlterModelOptions(
            name='jobsalary',
            options={'verbose_name': 'Job Salaries', 'verbose_name_plural': 'Job Salary'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Job Types', 'verbose_name_plural': 'Job Type'},
        ),
        migrations.AlterField(
            model_name='jobexperiencerange',
            name='range',
            field=models.CharField(help_text='Ex. Fresher / 2 Years / 2 - 4 Years', max_length=200, verbose_name='Experience Range'),
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='name',
            field=models.CharField(help_text='Ex. Delhi / Banglore', max_length=200, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(help_text='Ex. Full Time / Internship', max_length=200, verbose_name='Job type'),
        ),
    ]
