# Generated by Django 2.2.10 on 2021-11-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20211109_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Software Developer / Sales Manager', max_length=200, verbose_name='Job Profile Name')),
                ('locality', models.CharField(blank=True, help_text='Ex. Sector 62 / Central Delhi', max_length=200, null=True, verbose_name='Locality / District')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.JobExperienceRange')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.JobLocation')),
            ],
            options={
                'verbose_name': 'Job Profiles',
                'verbose_name_plural': 'Job Profile',
            },
        ),
    ]
