# Generated by Django 2.2.10 on 2021-11-09 08:26

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_custommustskilltag_mustskilltagged'),
        ('careers', '0004_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='must_have_skills',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.MustSkillTagged', to='tags.CustomMustSkillTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='skills',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.SkillTagged', to='tags.CustomSkillTag', verbose_name='Tags'),
        ),
    ]
