# Generated by Django 2.2.10 on 2021-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20211109_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobJoiningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Ex. Immediate / 0 - 15 Days', max_length=200, verbose_name='Joining Type')),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Joining Types',
                'verbose_name_plural': 'Job Joining type',
            },
        ),
    ]
