# Generated by Django 2.2.10 on 2021-11-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_jobjoiningtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='joining_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.JobJoiningType'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.JobExperienceRange'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.JobLocation'),
        ),
    ]
