# Generated by Django 2.2.10 on 2021-11-09 09:15

import careers.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_auto_20211109_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Joen Dave', max_length=250, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Ex. user@domain.com', max_length=200, verbose_name='Email ID')),
                ('city', models.CharField(help_text='Ex. Delhi / Bhubaneswar', max_length=200, verbose_name='City')),
                ('experience', models.CharField(help_text='Ex. Fresher / 1 Year', max_length=50, verbose_name='Experience')),
                ('notice_period', models.CharField(help_text='Ex. Immediate / 15 Days', max_length=150, verbose_name='Notice Period')),
                ('mobile_number', models.CharField(help_text='Ex. 9837xx-xxx01', max_length=10, verbose_name='Contact Number')),
                ('resume', models.FileField(blank=True, null=True, upload_to=careers.utils.applied_resume_upload_path, verbose_name='Resume')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.JobProfile')),
            ],
            options={
                'verbose_name': 'Applied Job Data',
                'verbose_name_plural': 'Applied Job Data',
            },
        ),
    ]
