# Generated by Django 2.2.10 on 2021-11-09 11:56

from django.db import migrations, models
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft Job'), ('Active', 'Active Job')], default='Draft', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='must_have_skills',
            field=taggit_selectize.managers.TaggableManager(help_text='Atleast add one', through='tags.MustSkillTagged', to='tags.CustomMustSkillTag', verbose_name='Must Have Skills'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='skills',
            field=taggit_selectize.managers.TaggableManager(help_text='Atleast add one', through='tags.SkillTagged', to='tags.CustomSkillTag', verbose_name='Add On Skills'),
        ),
    ]
