# Generated by Django 2.2.10 on 2021-11-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_auto_20211109_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='job_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.JobDomain'),
        ),
    ]
